spring.application.name=zeus
spring.datasource.name=postgres
spring.datasource.url=jdbc:postgresql://ls-ca6c97c84ddec9c1d377298c043e14eefb96f1da.c1wsqic661pc.eu-central-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=dbmasteruser
spring.datasource.password=oQb([AS;d`S=7iX2T?DT73.sVMI?Y>LF
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#spring.jpa.properties.hibernate.default_schema=postgres